# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sql.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

class Ui_Form(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ans = QtWidgets.QInputDialog.getMultiLineText(self, "Execute SQL", "Enter SQL query:")


    def retranslateUi(self):
        return self.ans


class FilterDialog(QtWidgets.QDialog):
    def __init__(self, headers):
        super().__init__()

        self.setWindowTitle("Filter Data")

        self.layout = QtWidgets.QVBoxLayout(self)

        self.header_list = QtWidgets.QComboBox()
        self.header_list.addItems(headers)
        self.layout.addWidget(self.header_list)

        self.value_input = QtWidgets.QLineEdit()
        self.layout.addWidget(self.value_input)

        self.buttons = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.StandardButton.Ok | QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttons.accepted.connect(self.accept)
        self.buttons.rejected.connect(self.reject)
        self.layout.addWidget(self.buttons)

    def get_values(self):
        return self.header_list.currentText(), self.value_input.text()